/**
 * The Card Utility Class:
 * 
 * This class consists of Utility functions that are dependent on an integer, dubbed 'card'.
 * This card integer is determined by {@link game#drawCard}, and the methods in this class process the variable generated by this function. 
 
 * @author Caden Hewlett
 *
 */
public class cardUtil {

	public cardUtil() {	}

	/**
	 * Determines the Numerical Value of a Card of an input Deck Index.
	 * 
	 * @param card The Random Card index generated by {@link game#drawCard}. 
	 * @return The actual numerical value (1 through 13) of the Card.
	 */
	public int determineValue(int card) {
		
		int value = 0;
		
		if(0 <= card && card <= 12) {
			value = card + 1;
		}
		
		else if(13 <= card && card <= 25) {
			value = card - 12;
		}
		
		else if(26 <= card && card <= 38) {
			value = card - 25;
		}
		else if(39 <= card && card < 52) {
			value = card - 38;
		}
		
		return value;
	}
	
	/**
	 * Determines the actual card itself given an index (as opposed to a numerical value).
	 * 
	 * @param card The Random Card index generated by {@link game#drawCard}. 
	 * @return A String in the style of 'Card-Name of Suit' 
	 */
	public String determineCard(int card) {
		
		//Defines local variables
		int value = 0;
		String suit = "";
		String cardNum = "";
		
		//Determines Suit based on Deck Index Ranges
		if(0 <= card && card <= 12) {
			suit = "Diamonds";
		}
		
		else if(13 <= card && card <= 25) {
			suit = "Hearts";
		}
		
		else if(26 <= card && card <= 38) {
			suit = "Spades";
		}
		
		else if(39 <= card && card < 52) {
			suit = "Clubs";
		}
		
		value = determineValue(card); //determines value using Value Function
		
		//Determines card name based on the value.
		
		if (value <= 10 && value != 1) { //if the card is not a face card or ace
			cardNum = String.valueOf(value); //take the string value of the number
		}
		else if (value == 1) {
			cardNum = "Ace"; //special case for Ace
		}
		else if (value == 11) {
			cardNum = "Jack"; //special case for Jack
		}
		else if (value == 12) {
			cardNum = "Queen"; //special case for Queen
		}
		else if (value == 13) {
			cardNum = "King"; //special case for King
		}
		
		return (cardNum + " of " + suit); //Combines the strings to determine the card
	}
	
}
